### ISSUE TITLE
Documentation of setting up a new dataset?

### ISSUE THREAD

**Issue by AngledLuffa** [hangyav/anchor-embeddings#2]
Hi!  I tried working through an example of Ottoman Turkish using modern Turkish as an anchor, and I came up with some questions on the process.  Some of the answers may be more widely applicable to people trying to use this tool.

These are the steps I'm started with:

- Convert the anchor word embedding to a text file: each line is word, embedding vector
- Build a text file for input, one paragraph per line
- Keep part of the text data as a reserve for testing?  Is that necessary?  There doesn't seem to be a dev or test split in the sample json
- Copy & edit the json for an experiment, putting in the new paths

I had a few questions regarding the json file for the experiments...  What is the difference between `train_dico` in `experiments` and `path_to_evaluation_file` in `evaluate`?  Can those just be the same dictionary?  `path_to_evaluation_file` is a predefined dictionary, right?

`experiments` field `tgt_emb_name` is probably the same as `evaluate` field `tgt_model_new_name`?  I'm not sure about that because there's also `tgt_emb_name` in the `evaluate` section

The documentation says to set `save_tgt_embeddings`, but the sample .json files have `save_tgt_embeddings_without_concat` instead.  Are both relevant or only the `...without_concat`?

Can we change it so absolute paths work as absolute paths without concat the current directory?  It looked for a file in `/home/john/anchor-embeddings/home/john/extern_data/ottoman/experiment/corpus_shuf.txt` for example when I gave it the absolute path to that file

A few more words about what it means to install MUSE might help!  Also, something about installing `faiss-gpu` (or `faiss-cpu`) from here: https://anaconda.org/pytorch/faiss-gpu although when I run, even after doing `pip3 install faiss-gpu`, it says "Impossible to import Faiss-GPU", which I don't understand.

I did `git clone git@github.com:facebookresearch/MUSE.git`, and when I ran the experiment, I got the following error.  Anyway, MUSE seems to have zero support on their github (nothing ever gets an answer), so maybe worthwhile to switch to something else if possible.

Any suggestions on getting past this would help.  For the MUSE step, is it required to have one of the hops be EN, or is TR going to be sufficient?  I believe there is some MUSE data for TR, but it's not working when it gets to this step.  I ran `get_evaluation.sh` as recommended on the MUSE website, but it doesn't seem to have downloaded anything TR related.

There is some file output in word_embeddings after 6 iterations starting from here:

```
Training w2v anchor embeddings with 4115 vectors
```

Is that the full training cycle?  It doesn't take too long, less than a minute, which I find surprisingly fast for word vectors.  We didn't have the full text dataset yet, though.

Error log from when it runs MUSE:

```
Running command:
/home/john/anchor-embeddings/anchor_venv/bin/python3 /home/john/anchor-embeddings/MUSE/evaluate.py --tgt_emb word_embeddings/ota_anchor_final.txt --src_emb ottoman/experiment/tr_emb.txt --tgt_lang ota --src_lang tr --dico_eval ottoman/experiment/dictionary.txt --exp_name tr_ota_chain --cuda True

Impossible to import Faiss-GPU. Switching to FAISS-CPU, this will be slower.

INFO - 12/12/24 23:26:37 - 0:00:00 - ============ Initialized logger ============
INFO - 12/12/24 23:26:37 - 0:00:00 - cuda: True
                                     dico_eval: ottoman/experiment/dictionary.txt
                                     emb_dim: 300
                                     exp_id:
                                     exp_name: tr_ota_chain
                                     exp_path: /home/john/anchor-embeddings/MUSE/dumped/tr_ota_chain/xf8nlnqbll
                                     max_vocab: 200000
                                     normalize_embeddings:
                                     src_emb: ottoman/experiment/tr_emb.txt
                                     src_lang: tr
                                     tgt_emb: word_embeddings/ota_anchor_final.txt
                                     tgt_lang: ota
                                     verbose: 2
INFO - 12/12/24 23:26:37 - 0:00:00 - The experiment will be stored in /home/john/anchor-embeddings/MUSE/dumped/tr_ota_chain/xf8nlnqbll
Traceback (most recent call last):
  File "/home/john/anchor-embeddings/MUSE/evaluate.py", line 49, in <module>
    src_emb, tgt_emb, mapping, _ = build_model(params, False)
  File "/home/john/anchor-embeddings/MUSE/src/models.py", line 46, in build_model
    src_dico, _src_emb = load_embeddings(params, source=True)
  File "/home/john/anchor-embeddings/MUSE/src/utils.py", line 406, in load_embeddings
    return read_txt_embeddings(params, source, full_vocab)
  File "/home/john/anchor-embeddings/MUSE/src/utils.py", line 280, in read_txt_embeddings
    assert _emb_dim_file == int(split[1])
AssertionError
Traceback (most recent call last):
  File "/home/john/anchor-embeddings/run_experiment.py", line 83, in <module>
    main()
  File "/home/john/anchor-embeddings/run_experiment.py", line 79, in main
    run_command(evaluate_command, data['evaluate'])
  File "/home/john/anchor-embeddings/run_experiment.py", line 14, in run_command
    raise Exception('Error in subprocess!')
Exception: Error in subprocess!
```

Thanks in advance for the help!

**Comment by hangyav** [comment]
Hi,

> Keep part of the text data as a reserve for testing? Is that necessary? There doesn't seem to be a dev or test split in the sample json

Raw text data for testing is not used but a test dictionary (word translation pairs) could come handy to check how good the resulting aligned embedding space is.

> What is the difference between `train_dico` in `experiments` and `path_to_evaluation_file` in `evaluate`? Can those just be the same dictionary? `path_to_evaluation_file` is a predefined dictionary, right?

`train_dico` is the training dictionary (the anchor points in our papers) when building the embeddings jointly for two languages, while `path_to_evaluation_file` is the evaluation dictionary to check how good the embeddings are. Non-overlapping dictionaries should be used.

> `experiments` field `tgt_emb_name` is probably the same as `evaluate` field `tgt_model_new_name`? I'm not sure about that because there's also `tgt_emb_name` in the `evaluate` section

Yes they are the same (`tgt_emb_name` in the `evaluate` section should not be used)

> The documentation says to set `save_tgt_embeddings`, but the sample .json files have `save_tgt_embeddings_without_concat` instead. Are both relevant or only the `...without_concat`?

The `save_tgt_embeddings_without_concat` is a boolean flag that should be set to `true` in the last step (item of the `experiments`; since I believe you only have one such step you should set it to `true`), otherwise false. `save_tgt_embeddings` is a typo, thanks for pointing out!

> Can we change it so absolute paths work as absolute paths without concat the current directory? It looked for a file in `/home/john/anchor-embeddings/home/john/extern_data/ottoman/experiment/corpus_shuf.txt` for example when I gave it the absolute path to that file

Currently every path should be relative to the project root. 

> Is that the full training cycle? It doesn't take too long, less than a minute, which I find surprisingly fast for word vectors. We didn't have the full text dataset yet, though.

With a small input corpus it runs quite fast, yes.

> Any suggestions on getting past this would help. For the MUSE step, is it required to have one of the hops be EN, or is TR going to be sufficient?

EN is not necessary, any other language can be used as long as you have a dictionary for that language pair. Based on the error log it seems to me that it has to do with the embedding dimensions. Are you using 300 dimensional embeddings and do both of your files (`ottoman/experiment/tr_emb.txt` and `word_embeddings/ota_anchor_final.txt`) have a proper header (`<num_words> <dim>`)?

> A few more words about what it means to install MUSE might help!

The simplest way to install MUSE is just to clone it at the `anchor-embedding` project root and download the necessary resources as described by MUSE's readme.

> Also, something about installing `faiss-gpu` (or `faiss-cpu`) from here: https://anaconda.org/pytorch/faiss-gpu although when I run, even after doing `pip3 install faiss-gpu`, it says "Impossible to import Faiss-GPU", which I don't understand.

Currently the `requirements.txt` includes `faiss-cpu` as the dependency for simplicity. Could you try installing `faiss-gpu` manually? We should mention it in the readme.

**Comment by AngledLuffa** [comment]
I did try installing faiss-gpu manually.  Still wasn't able to get the evaluation step working.  

Ultimately it's not a huge deal if MUSE isn't working, as the plan was to use the vectors immediately in downstream tasks to see if they are better than using the related language's vectors directly.  Since the languages we initially tried on are TR and OTA, the TR word vectors actually work reasonably well for OTA.  Perhaps more data would help as well.  There are other combinations we also want to try, such as KYV - FI.  We'll report back results as we get them

**Comment by AngledLuffa** [comment]
Thanks for the help!
